

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#fafafa]" suppressHydrationWarning={true}>
        <Navbar />
        <div className="flex justify-center mb-5">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
