import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { ConfigProvider } from "antd";
import theme from "@/ui/configs/Theme";
import Navbar from "@/ui/components/navbar";

import "@/ui/configs/scrollConfig.css"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
          <body className="tw-min-h-[100dvh] tw-bg-[#f5f5f5]">
            <Navbar />
            {children}
          </body>
        </ConfigProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
