import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { ConfigProvider } from "antd";
import theme from "@/ui/configs/Theme";
import Navbar from "@/ui/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<link
  rel="icon"
  href="/icon?<generated>"
  type="image/<generated>"
  sizes="<generated>"
/>

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
          <body className="min-h-[100dvh] bg-[#f5f5f5]">
            <Navbar />
            {children}
          </body>
        </ConfigProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
