import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { ConfigProvider } from "antd";
import theme from "@/ui/configs/Theme";
import Navbar from "@/ui/components/navbar";
import ImageSlider from "@/ui/components/swiper/ImageSlider";

import "@/ui/configs/scrollConfig.css";
import "./globals.css";
import Location from "@/ui/components/location";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
                <body className="tw-min-h-[100vh] tw-bg-[#f5f5f5] tw-flex tw-flex-col tw-items-center tw-justify-center">
                  <Navbar />
                        <div className="tw-w-[91%] max-md:tw-w-[96%] tw-mb-3">
                          <ImageSlider />
                          {/* <Location /> */}
                        </div>
                  {children}
                </body>
        </ConfigProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
